# Generated by Django 6.1.1 on 2026-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certification_remove_education_is_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='image',
        ),
        migrations.AddField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, help_text='Upload an image or PDF', null=True, upload_to='certificates/'),
        ),
    ]
