# Generated by Django 6.1.1 on 2026-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_certification_image_certification_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
